In [1]:
import pandas as pd

In [29]:
# From dictionary
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [30]:
# From list of lists
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [31]:
#inspecting dataas
df.head()  	# First 5 rows

    Name  Age
0  Alice   25
1    Bob   30

In [32]:
df.tail()  	# Last 5 rows

    Name  Age
0  Alice   25
1    Bob   30

In [33]:
df.info()  	# Info about DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

In [34]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [35]:
# Column selection
df['Name']

0    Alice
1      Bob
Name: Name, dtype: object

In [36]:
df[['Name', 'Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [37]:
# Row selection by label and position
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [38]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [39]:
#filtering data
df[df['Age'] > 25]  # Rows where Age > 25

  Name  Age
1  Bob   30

In [40]:
#adding and removing of columns
df['Gender'] = ['F', 'M']  # Add new column
print(df)
df.drop('Age', axis=1, inplace=True)  # Remove column
print(df)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M
    Name Gender
0  Alice      F
1    Bob      M

In [41]:
#handling missing data
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [42]:
df.dropna()

    Name Gender
0  Alice      F
1    Bob      M

In [43]:
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [46]:
#grouping
df['Age'] = [25, 30]
print(df.groupby('Gender')['Age'].mean())

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [49]:
# Merge two DataFrames
data1 = {'Name': ['sarah', 'james'], 'Age': [25, 27]}
df1 = pd.DataFrame(data1)
data2 = {'Name':['sarah','james'],'subject': ['maths', 'english'], 'marks': [70, 77]}
df2 = pd.DataFrame(data2)
print(pd.merge(df1, df2, on='Name'))

    Name  Age  subject  marks
0  sarah   25    maths     70
1  james   27  english     77

In [58]:
# Join by index
data1 = {'Name': ['sarah', 'james'], 'Age': [25, 27]}
df3 = pd.DataFrame(data1)
data2 = {'Name':['sarah','james'],'subject': ['maths', 'english'], 'marks': [70, 77]}
df4 = pd.DataFrame(data2)
df3.set_index('Name').join(df4.set_index('Name'))

       Age  subject  marks
Name
sarah   25    maths     70
james   27  english     77

In [66]:
df.to_csv('data.csv', index=False)
df = pd.read_csv('data.csv')
print(df)

    Name Gender  Age
0  Alice      F   25
1    Bob      M   30

In [67]:
# Write CSV
df.to_csv('output.csv', index=False)

In [69]:
#useful functions
df.sort_values('Age')

    Name Gender  Age
0  Alice      F   25
1    Bob      M   30

In [70]:
df['Age'].apply(lambda x: x + 1)

0    26
1    31
Name: Age, dtype: int64

In [71]:
df['Name'].unique()

array(['Alice', 'Bob'], dtype=object)

In [72]:
df['Age'].value_counts()

Age
25    1
30    1
Name: count, dtype: int64